model_list:
  - model_name: local-coder
    litellm_params:
      model: ollama/qwen2.5-coder:32b
      api_base: http://host.docker.internal:11434
  - model_name: claude-4.6
    litellm_params:
      model: openrouter/anthropic/claude-4.6
      api_key: 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
  - model_name: gemini-3-flash
    litellm_params:
      model: gemini/gemini-3-flash
      api_key: AIzaSyDYQoCMC3oG5JQtm4XfUW-2aX-KRALvd1o
  - model_name: gemini-3.1-pro-thinking
    litellm_params:
      model: gemini/gemini-3.1-pro-preview
      api_key: AIzaSyDYQoCMC3oG5JQtm4XfUW-2aX-KRALvd1o
  - model_name: glm-4-reasoner
    litellm_params:
      model: openrouter/zhipu/glm-4
      api_key: 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
